### ISSUE TITLE
Incorrect volume mapping in docker run for engines

### ISSUE THREAD

**Issue by viddagrava** [qltysh/codeclimate#1023]
Hey guys,
thanks a lot for the good work. Nonetheless, I believe there's an issue with how the wrapper runs the engines.
I am trying to run the container in a gitlab pipeline with the following:
```
code_quality:
  stage: test
  variables:
    NETWORK_MODE: host
  image:
    name: codeclimate/codeclimate
    entrypoint: ["/bin/ash", "-c"]
  script:
    - CODECLIMATE_DOCKER=1 CODECLIMATE_DEBUG=1 CODECLIMATE_CODE=/builds/<workspace>/<project>/ /usr/src/app/bin/codeclimate analyze
```

and this is the output I get:
```
$ CODECLIMATE_DOCKER=1 CODECLIMATE_DEBUG=1 CODECLIMATE_CODE=/builds/<workspace>/<project>/ /usr/src/app/bin/codeclimate analyze
I, [2021-06-09T09:27:28.492917 #9]  INFO -- : starting engine structure
D, [2021-06-09T09:27:28.496019 #9] DEBUG -- : /config.json content: {"enabled"=>true, "channel"=>"stable", "include_paths"=>["<file from repo>"], "debug"=>"1"}
D, [2021-06-09T09:27:28.504171 #9] DEBUG -- : docker run: ["docker", "run", "--name", "cc-engines-structure-stable-009c6e74-434d-44df-a7c6-aa577b45f33b", "--cap-drop", "all", "--label", "com.codeclimate.label=63ddc812-5acd-4d0e-a2f3-f334af8a660b", "--log-driver", "none", "--memory-swap", "-1", "--net", "none", "--rm", "--volume", "/builds/<workspace>/<project>/:/code:ro", "--volume", "/tmp/cc/18cfcc2e-704c-4334-9912-7525b306d2fc:/config.json:ro", "--user", "9000:9000", "--memory", "1024000000", "codeclimate/codeclimate-structure"]
D, [2021-06-09T09:27:28.780563 #9] DEBUG -- : engine stderr: 12
D, [2021-06-09T09:27:28.780684 #9] DEBUG -- : engine stderr: Parser process id: 12
D, [2021-06-09T09:27:28.781085 #9] DEBUG -- : engine stderr: codeclimate-parser socket not present
D, [2021-06-09T09:27:28.781149 #9] DEBUG -- : engine stderr: waiting 1s...
D, [2021-06-09T09:27:30.163807 #9] DEBUG -- : engine stderr: bin/structure:21:in `read': Is a directory @ io_fread - /config.json (Errno::EISDIR)
D, [2021-06-09T09:27:30.163935 #9] DEBUG -- : engine stderr: 	from bin/structure:21:in `<main>'
I, [2021-06-09T09:27:30.260833 #9]  INFO -- : finished engine structure`
```

why is the tmp folder path mapped to config.json (`/tmp/cc/18cfcc2e-704c-4334-9912-7525b306d2fc:/config.json:ro`)?

I guess the problem lies here (codeclimate/lib/cc/analyzer/engine.rb: line 76-92):
especially line 85:
`"--volume", "#{config_file.host_path}:/config.json:ro",`

Thanks in advance.
David
