### ISSUE TITLE
Allow import for external .codeclimate.yml configurations

### ISSUE THREAD

**Issue by GarreBrenn** [qltysh/codeclimate#1026]
I am working on triggering code quality tests on multiple GitLab repositories from the CI/CD flow of a single GitLab project. We have decided on a .codeclimate.yml configuration that should work for all of our projects. It would be nice to not have to physically copy that configuration into every single project we intend to test, as there are likely 100+ and manually updating these in the case of a change to our default configuration would be quite cumbersome.

While it's documented that you can use [external configurations for _engines_](https://docs.codeclimate.com/docs/configuring-the-prepare-step), I don't see any documentation relating to using external .codeclimate.yml files. It would be great if we could instead include a configuration file like:

```
# here you can see the ability to include several configurations 
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/thoughtbot/guides/master/.codeclimate.yml"
    path: ".codeclimate.yml"
    name: cc_config_1
  - url: "https://raw.githubusercontent.com/thoughtbot/guides/feature/.codeclimate.yml"
    path: ".codeclimate.yml"
    name: cc_config_2

# here you could specify which codeclimate configurations you would like to enable
codeclimate:
  cc_config_1
    enabled: true
  cc_config_2
    enabled: false

# below here would add to or override the included configuration
plugins:
...
```

I apologize if this feature already exists, but if it does, this could serve as a reminder that the documentation is unclear.
