### ISSUE TITLE
Reek configuration custom location

### ISSUE THREAD

**Issue by bestwebua** [qltysh/codeclimate#1078]
Hi there! Thanks for awesome tool. I have a question. Is it possible to specify custom Reek configuration location like in `.codeclimate.yml` below?

```yml
checks:
  argument-count:
    enabled: false
  method-complexity:
    enabled: false

plugins:
  rubocop:
    enabled: true
    channel: rubocop-1-39
    config:
      file: .circleci/linter_configs/.rubocop.yml

  reek:
    enabled: true
    config:
      file: .circleci/linter_configs/.reek.yml
```

Rubocop applies, but Reek doesn't. Thanks for advice!
