### ISSUE TITLE
Issue using codeclimate docker image directly as part of gitlab cicd pipeline

### ISSUE THREAD

**Issue by patpatpat123** [qltysh/codeclimate#1134]
Hello,

First of all, I wanted to say thank you for this project.
I just wanted to reach out, as I am facing an issue with the CodeClimate Docker image, as part of the GitLab CI/CD pipeline.

What I would like to achieve:
Run CodeClimate as part of GitLab CI/CD without having to go through the whole docker Docker-in-Docker + Docker image pull setup (since this has performance drawbacks).

What did I try:
Using this code:
```
codeclimateworking:
  image: docker:stable
 script:
    - docker pull codeclimate/codeclimate:latest
    - docker run --env CODECLIMATE_CODE="$PWD" --volume "$PWD":/code --volume /var/run/docker.sock:/var/run/docker.sock --volume /tmp/cc:/tmp/cc codeclimate/codeclimate:latest analyze -f json > gl2-code-quality-report.json || true
     services:
    - docker:dind
  artifacts:
    paths: [ gl2-code-quality-report.json ]
    reports:
      codequality: gl2-code-quality-report.json
```

Above is **working** however, it has some drawbacks, as it requires to first pull docker itself, then using the docker in docker approach, invoke codeclimate.

I hope to achieve the same result by using this:

```
codequalitybad:
  image:
    name: codeclimate/codeclimate:latest
    entrypoint: ['']
  services:
    - docker:dind
  variables:
    CODECLIMATE_DEBUG: 'true'
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [ "gl1-code-quality-report.json" ]
    reports:
      codequality: gl1-code-quality-report.json
  script:
  - analyze -f json > gl1-code-quality-report.json || true
```

I was hoping this would trigger the scan.
However, this is not working, codeclimat is not being invoked at all.

Could you please help me on this issue?
Thank you
